config/routes.rb
  put "users/:username/preferences/avatar/pick" => "users#pick_avatar", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/preferences/card-badge" => "users#card_badge", constraints: {username: USERNAME_ROUTE_FORMAT}
  put "users/:username/preferences/card-badge" => "users#update_card_badge", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/staff-info" => "users#staff_info", constraints: {username: USERNAME_ROUTE_FORMAT}

  get "users/:username/invited" => "users#invited", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/invited_count" => "users#invited_count", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/invited/:filter" => "users#invited", constraints: {username: USERNAME_ROUTE_FORMAT}
  post "users/action/send_activation_email" => "users#send_activation_email"
  get "users/:username/activity" => "users#show", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/activity/:filter" => "users#show", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/badges" => "users#show", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/notifications" => "users#show", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/pending" => "users#show", constraints: {username: USERNAME_ROUTE_FORMAT}
  delete "users/:username" => "users#destroy", constraints: {username: USERNAME_ROUTE_FORMAT}
  # The external_id constraint is to allow periods to be used in the value without becoming part of the format. ie: foo.bar.json
  get "users/by-external/:external_id" => "users#show", constraints: {external_id: /[^\/]+/}
  get "users/:username/flagged-posts" => "users#show", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/deleted-posts" => "users#show", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "user-badges/:username.json" => "user_badges#username", constraints: {username: USERNAME_ROUTE_FORMAT}, defaults: {format: :json}
  get "user-badges/:username" => "user_badges#username", constraints: {username: USERNAME_ROUTE_FORMAT}

  post "user_avatar/:username/refresh_gravatar" => "user_avatars#refresh_gravatar", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "letter_avatar/:username/:size/:version.png" => "user_avatars#show_letter", format: false, constraints: { hostname: /[\w\.-]+/, size: /\d+/, username: USERNAME_ROUTE_FORMAT}
  get "user_avatar/:hostname/:username/:size/:version.png" => "user_avatars#show", format: false, constraints: { hostname: /[\w\.-]+/, size: /\d+/, username: USERNAME_ROUTE_FORMAT }

  get "highlight-js/:hostname/:version.js" => "highlight_js#show", format: false, constraints: { hostname: /[\w\.-]+/ }

  get "stylesheets/:name.css" => "stylesheets#show", constraints: { name: /[a-z0-9_]+/ }

  post "uploads" => "uploads#create"

  # used to download original images
  get "uploads/:site/:sha" => "uploads#show", constraints: { site: /\w+/, sha: /[a-f0-9]{40}/ }
  # used to dowwload attachments
  get "uploads/:site/original/:tree:sha" => "uploads#show", constraints: { site: /\w+/, tree: /(\w+\/)+/i, sha: /[a-f0-9]{40}/ }
  # used to download attachments (old route)
  get "uploads/:site/:id/:sha" => "uploads#show", constraints: { site: /\w+/, id: /\d+/, sha: /[a-f0-9]{16}/ }

  get "posts" => "posts#latest"
  get "posts/by_number/:topic_id/:post_number" => "posts#by_number"
  get "posts/:id/reply-history" => "posts#reply_history"
  get "posts/:username/deleted" => "posts#deleted_posts", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "posts/:username/flagged" => "posts#flagged_posts", constraints: {username: USERNAME_ROUTE_FORMAT}

  resources :groups do
    get 'members'
    get 'posts'
    get 'counts'

    put "members" => "groups#add_members"
    delete "members/:username" => "groups#remove_member"
  end

  # In case people try the wrong URL
  get '/group/:id', to: redirect('/groups/%{id}')
  get '/group/:id/members', to: redirect('/groups/%{id}/members')

  resources :posts do
    put "bookmark"
    put "wiki"
    put "post_type"
    put "rebake"
    put "unhide"
    get "replies"
    get "revisions/latest" => "posts#latest_revision"
    get "revisions/:revision" => "posts#revisions", constraints: { revision: /\d+/ }
    put "revisions/:revision/hide" => "posts#hide_revision", constraints: { revision: /\d+/ }
    put "revisions/:revision/show" => "posts#show_revision", constraints: { revision: /\d+/ }
    put "recover"
    collection do
      delete "destroy_many"
    end
  end

  get 'notifications' => 'notifications#index'
  put 'notifications/mark-read' => 'notifications#mark_read'

  match "/auth/:provider/callback", to: "users/omniauth_callbacks#complete", via: [:get, :post]
  match "/auth/failure", to: "users/omniauth_callbacks#failure", via: [:get, :post]

  resources :clicks do
    collection do
      get "track"
    end
  end

  get "excerpt" => "excerpt#show"

  resources :post_action_users
  resources :post_actions do
    collection do
      get "users"
      post "defer_flags"
    end
  end
  resources :user_actions

  resources :badges, only: [:index]
  get "/badges/:id(/:slug)" => "badges#show"
  resources :user_badges, only: [:index, :create, :destroy]


  get '/c', to: redirect('/categories')

  resources :categories, :except => :show
  post "category/:category_id/move" => "categories#move"
  post "categories/reorder" => "categories#reorder"
  post "category/:category_id/notifications" => "categories#set_notifications"
  put "category/:category_id/slug" => "categories#update_slug"

  get "c/:id/show" => "categories#show"
  get "c/:category.rss" => "list#category_feed", format: :rss
  get "c/:parent_category/:category.rss" => "list#category_feed", format: :rss
  get "c/:category" => "list#category_latest"
  get "c/:category/none" => "list#category_none_latest"
  get "c/:parent_category/:category" => "list#parent_category_category_latest"
  get "c/:category/l/top" => "list#category_top", as: "category_top"
  get "c/:category/none/l/top" => "list#category_none_top", as: "category_none_top"
  get "c/:parent_category/:category/l/top" => "list#parent_category_category_top", as: "parent_category_category_top"


  TopTopic.periods.each do |period|
    get "top/#{period}" => "list#top_#{period}"
    get "c/:category/l/top/#{period}" => "list#category_top_#{period}", as: "category_top_#{period}"
    get "c/:category/none/l/top/#{period}" => "list#category_none_top_#{period}", as: "category_none_top_#{period}"
    get "c/:parent_category/:category/l/top/#{period}" => "list#parent_category_category_top_#{period}", as: "parent_category_category_top_#{period}"
  end

  Discourse.anonymous_filters.each do |filter|
    get "#{filter}.rss" => "list##{filter}_feed", format: :rss
  end

  Discourse.filters.each do |filter|
    get "#{filter}" => "list##{filter}", constraints: { format: /(json|html)/ }
    get "c/:category/l/#{filter}" => "list#category_#{filter}", as: "category_#{filter}"
    get "c/:category/none/l/#{filter}" => "list#category_none_#{filter}", as: "category_none_#{filter}"
    get "c/:parent_category/:category/l/#{filter}" => "list#parent_category_category_#{filter}", as: "parent_category_category_#{filter}"
  end

  get "category/*path" => "categories#redirect"

  get "top" => "list#top"
  get "search/query" => "search#query"
  get "search" => "search#show"

  # Topics resource
  get "t/:id" => "topics#show"
  post "t" => "topics#create"
  put "t/:id" => "topics#update"
  delete "t/:id" => "topics#destroy"
  put "topics/bulk"
  put "topics/reset-new" => 'topics#reset_new'
  post "topics/timings"

  get 'topics/similar_to' => 'similar_topics#index'
  resources :similar_topics

  get "topics/feature_stats"
  get "topics/created-by/:username" => "list#topics_by", as: "topics_by", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "topics/private-messages/:username" => "list#private_messages", as: "topics_private_messages", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "topics/private-messages-sent/:username" => "list#private_messages_sent", as: "topics_private_messages_sent", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "topics/private-messages-unread/:username" => "list#private_messages_unread", as: "topics_private_messages_unread", constraints: {username: USERNAME_ROUTE_FORMAT}

  get 'embed/comments' => 'embed#comments'
  get 'embed/count' => 'embed#count'
  get 'embed/info' => 'embed#info'

  get "new-topic" => "list#latest"

  # Topic routes
  get "t/id_for/:slug" => "topics#id_for_slug"
  get "t/:slug/:topic_id/wordpress" => "topics#wordpress", constraints: {topic_id: /\d+/}
  get "t/:topic_id/wordpress" => "topics#wordpress", constraints: {topic_id: /\d+/}
  get "t/:slug/:topic_id/moderator-liked" => "topics#moderator_liked", constraints: {topic_id: /\d+/}
  get "t/:slug/:topic_id/summary" => "topics#show", defaults: {summary: true}, constraints: {topic_id: /\d+/}
  get "t/:slug/:topic_id/unsubscribe" => "topics#unsubscribe", constraints: {topic_id: /\d+/}
  get "t/:topic_id/unsubscribe" => "topics#unsubscribe", constraints: {topic_id: /\d+/}
  get "t/:topic_id/summary" => "topics#show", constraints: {topic_id: /\d+/}
  put "t/:slug/:topic_id" => "topics#update", constraints: {topic_id: /\d+/}
  put "t/:slug/:topic_id/star" => "topics#star", constraints: {topic_id: /\d+/}
  put "t/:topic_id/star" => "topics#star", constraints: {topic_id: /\d+/}
  put "t/:slug/:topic_id/status" => "topics#status", constraints: {topic_id: /\d+/}
  put "t/:topic_id/status" => "topics#status", constraints: {topic_id: /\d+/}
  put "t/:topic_id/clear-pin" => "topics#clear_pin", constraints: {topic_id: /\d+/}
  put "t/:topic_id/re-pin" => "topics#re_pin", constraints: {topic_id: /\d+/}
  put "t/:topic_id/mute" => "topics#mute", constraints: {topic_id: /\d+/}
  put "t/:topic_id/unmute" => "topics#unmute", constraints: {topic_id: /\d+/}

app/helpers/topics_helper.rb
module TopicsHelper

  def render_topic_title(topic)
    link_to(topic.title,topic.relative_url)
  end

  def categories_breadcrumb(topic)
    breadcrumb = []

    category = topic.category
    if category && !category.uncategorized?
      if (parent = category.parent_category)
        breadcrumb.push url: parent.url, name: parent.name
      end
      breadcrumb.push url: category.url, name: category.name
    end
    Plugin::Filter.apply(:topic_categories_breadcrumb, topic, breadcrumb)
  end

end

app/views/topics/plain.html.erb
<!DOCTYPE html>
<html lang="<%=SiteSetting.default_locale%>">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title><%= @topic_view.topic.title %></title>
  <%= raw crawlable_meta_data(title: @topic_view.title, description: @topic_view.summary, image: @topic_view.image_url) %>
</head>
<body>
<% @topic_view.posts.each do |post| %>
  <% if post.user %>
    <div class='creator'>
      <b><%= post.user.username %></b> <%= "(#{post.user.name})" if (SiteSetting.display_name_on_posts && SiteSetting.enable_names?) %> at <%= post.created_at.to_formatted_s(:long_ordinal) %> — #<%= post.post_number %>
    </div>
    <div class='post'>
      <% if post.hidden %>
        <%= t('flagging.user_must_edit').html_safe %>
      <% else %>
        <%= post.cooked.html_safe %>
      <% end %>
    </div>
    <hr/>
  <% end %>
<% end %>
<p>
  <% if @topic_view.prev_page %>
    <%= link_to t(:prev_page), @topic_view.prev_page_path, rel: 'prev' %>
  <% end %>
  <% if @topic_view.next_page %>
    <b><%= link_to t(:next_page), @topic_view.next_page_path, rel: 'next' %></b>
  <% end %>
</p>
</body>

app/views/topics/show.html.erb
<h1>
  <%= render_topic_title(@topic_view.topic) %>
</h1>

<% @breadcrumbs = categories_breadcrumb(@topic_view.topic)
    if @breadcrumbs.present? %>
<div id='breadcrumbs'>
  <% @breadcrumbs.each_with_index do |c,i| %>
    <div id="breadcrumb-<%=i%>" itemscope itemtype="http://data-vocabulary.org/Breadcrumb"
      <%-if (i+1) < @breadcrumbs.length%>
        itemref="breadcrumb-<%=(i+1)%>"
      <%-end%>>
      <a href="<%=c[:url]%>" itemprop="url">
        <span itemprop="title"><%=c[:name]%></span>
      </a>
    </div>
  <% end %>
</div>
<% end %>
<%= server_plugin_outlet "topic_header" %>
<hr>

<% @topic_view.posts.each do |post| %>
  <div itemscope itemtype='http://schema.org/Article'>
    <% if (u = post.user) %>
      <div class='creator'>
        <span>
          <a href='<%= Discourse.base_uri %>/users/<%= u.username %>'><b itemprop='author'><%= u.username %></b></a>
           <%= "(#{u.name})" if (SiteSetting.display_name_on_posts && SiteSetting.enable_names? && !u.name.blank?) %>
           <time datetime='<%= post.created_at.to_formatted_s(:iso8601) %>' itemprop='datePublished'>
             <%= post.created_at %>
           </time>
        </span>
        <span itemprop='position'>#<%= post.post_number %></span>
      </div>
      <div class='post' itemprop='articleBody'>
        <%= post.hidden ? t('flagging.user_must_edit').html_safe : post.cooked.html_safe %>
      </div>
      <meta itemprop='interactionCount' content='UserLikes:<%= post.like_count %>'>
      <meta itemprop='interactionCount' content='UserComments:<%= post.reply_count %>'>
      <hr>
    <% end %>
  </div>
<% end %>

<% if @topic_view.prev_page || @topic_view.next_page %>
  <div role='navigation' itemscope itemtype='http://schema.org/SiteNavigationElement'>
    <% if @topic_view.prev_page %>
      <span itemprop='url'><%= link_to t(:prev_page), @topic_view.prev_page_path, rel: 'prev', itemprop: 'name' %></span>
    <% end %>
    <% if @topic_view.next_page %>
      <span itemprop='url'><b><%= link_to t(:next_page), @topic_view.next_page_path, rel: 'next', itemprop: 'name' %></b></span>
    <% end %>
  </div>
<% end %>

<% content_for :head do %>
  <%= auto_discovery_link_tag(@topic_view, {action: :feed, slug: @topic_view.topic.slug, topic_id: @topic_view.topic.id}, title: t('rss_posts_in_topic', topic: @topic_view.title), type: 'application/rss+xml') %>
  <%= raw crawlable_meta_data(title: @topic_view.title, description: @topic_view.summary, image: @topic_view.image_url) %>
<% end %>

<% content_for(:title) { "#{@topic_view.page_title}" } %>

app/views/topics/show.rss.erb
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <% topic_url = @topic_view.absolute_url %>
    <% lang = SiteSetting.find_by_name('default_locale').try(:value) %>
    <% site_email = SiteSetting.find_by_name('contact_email').try(:value) %>
    <title><%= @topic_view.title %></title>
    <link><%= topic_url %></link>
    <description><%= @topic_view.posts.first.raw %></description>
    <%= "<language>#{lang}</language>" if lang %>
    <lastBuildDate><%= @topic_view.topic.bumped_at.rfc2822 %></lastBuildDate>
    <category><%= @topic_view.topic.category.name %></category>
    <atom:link href="<%= topic_url %>.rss" rel="self" type="application/rss+xml" />
    <% @topic_view.recent_posts.each do |post| %>
      <% next unless post.user %>
      <item>
        <title><%= @topic_view.title %></title>
        <dc:creator><![CDATA[<%= "@#{post.user.username}#{" #{post.user.name}" if (post.user.name.present? && SiteSetting.enable_names?)}" -%>]]></dc:creator>
        <description><![CDATA[
          <% post_url = Discourse.base_url + post.url %>
          <p><%= t('author_wrote', author: link_to("@#{post.user.username}", user_url(post.user.username_lower))).html_safe %></p>
          <blockquote>
            <% if post.hidden %>
              <%= t('flagging.user_must_edit').html_safe %>
            <% else %>
              <%= post.cooked.html_safe %>
            <% end %>
          </blockquote>
          <p><%= link_to t('read_full_topic'), post_url %></p>
        ]]></description>
        <link><%= post_url %></link>
        <pubDate><%= post.created_at.rfc2822 %></pubDate>
        <guid isPermaLink="false">post-<%= post.topic_id %>-<%= post.post_number %></guid>
        <source url="<%= @topic_view.absolute_url %>.rss"><%= @topic_view.title %></source>
      </item>
    <% end %>
  </channel>
</rss>