config/routes.rb
require "sidekiq/web"
require_dependency "scheduler/web"
require_dependency "admin_constraint"
require_dependency "staff_constraint"
require_dependency "homepage_constraint"
require_dependency "permalink_constraint"

# This used to be User#username_format, but that causes a preload of the User object
# and makes Guard not work properly.
USERNAME_ROUTE_FORMAT = /[A-Za-z0-9\_.\-]+/ unless defined? USERNAME_ROUTE_FORMAT

BACKUP_ROUTE_FORMAT = /[a-zA-Z0-9\-_]*\d{4}(-\d{2}){2}-\d{6}\.(tar\.gz|t?gz)/i unless defined? BACKUP_ROUTE_FORMAT

Discourse::Application.routes.draw do

  match "/404", to: "exceptions#not_found", via: [:get, :post]
  get "/404-body" => "exceptions#not_found_body"

  if Rails.env.development?
    mount Sidekiq::Web => "/sidekiq"
    mount Logster::Web => "/logs"
  else
    mount Sidekiq::Web => "/sidekiq", constraints: AdminConstraint.new
    mount Logster::Web => "/logs", constraints: AdminConstraint.new
  end

  resources :about do
    collection do
      get "live_post_counts"
    end
  end

  resources :directory_items

  get "site" => "site#site"
  namespace :site do
    get "settings"
    get "custom_html"
    get "banner"
    get "emoji"
  end
  get "site_customizations/:key" => "site_customizations#show"

  resources :forums
  get "srv/status" => "forums#status"

  namespace :admin, constraints: StaffConstraint.new do
    get "" => "admin#index"

    get 'plugins' => 'plugins#index'

    resources :site_settings, constraints: AdminConstraint.new do
      collection do
        get "category/:id" => "site_settings#index"
      end
    end

    get "reports/:type" => "reports#show"

    resources :groups, constraints: AdminConstraint.new do
      collection do
        post "refresh_automatic_groups" => "groups#refresh_automatic_groups"
        get 'bulk'
        get 'bulk-complete' => 'groups#bulk'
        put 'bulk' => 'groups#bulk_perform'
      end
      member do
        put "members" => "groups#add_members"
        delete "members" => "groups#remove_member"
      end
    end

    get "groups/:type" => "groups#show", constraints: AdminConstraint.new
    get "groups/:type/:id" => "groups#show", constraints: AdminConstraint.new

    get "users/:id.json" => 'users#show' , id: USERNAME_ROUTE_FORMAT, defaults: {format: 'json'}
    resources :users, id: USERNAME_ROUTE_FORMAT do
      collection do
        get "list/:query" => "users#index"
        get "ip-info" => "users#ip_info"
        delete "delete-others-with-same-ip" => "users#delete_other_accounts_with_same_ip"
        get "total-others-with-same-ip" => "users#total_other_accounts_with_same_ip"
        put "approve-bulk" => "users#approve_bulk"
        delete "reject-bulk" => "users#reject_bulk"
      end
      put "suspend"
      put "delete_all_posts"
      put "unsuspend"
      put "revoke_admin", constraints: AdminConstraint.new
      put "grant_admin", constraints: AdminConstraint.new
      post "generate_api_key", constraints: AdminConstraint.new
      delete "revoke_api_key", constraints: AdminConstraint.new
      put "revoke_moderation", constraints: AdminConstraint.new
      put "grant_moderation", constraints: AdminConstraint.new
      put "approve"
      post "refresh_browsers", constraints: AdminConstraint.new
      post "log_out", constraints: AdminConstraint.new
      put "activate"
      put "deactivate"
      put "block"
      put "unblock"
      put "trust_level"
      put "trust_level_lock"
      put "primary_group"
      post "groups" => "users#add_group", constraints: AdminConstraint.new
      delete "groups/:group_id" => "users#remove_group", constraints: AdminConstraint.new
      get "badges"
      get "leader_requirements" => "users#tl3_requirements"
      get "tl3_requirements"
      put "anonymize"
    end


    post "users/sync_sso" => "users#sync_sso", constraints: AdminConstraint.new
    post "users/invite_admin" => "users#invite_admin", constraints: AdminConstraint.new

    resources :impersonate, constraints: AdminConstraint.new

    resources :email, constraints: AdminConstraint.new do
      collection do
        post "test"
        get "all"
        get "sent"
        get "skipped"
        get "preview-digest" => "email#preview_digest"
        post "handle_mail"
      end
    end

    scope "/logs" do
      resources :staff_action_logs,     only: [:index]
      resources :screened_emails,       only: [:index, :destroy]
      resources :screened_ip_addresses, only: [:index, :create, :update, :destroy] do
        collection do
          post "roll_up"
        end
      end
      resources :screened_urls,         only: [:index]
    end

    get "/logs" => "staff_action_logs#index"

    get "customize" => "color_schemes#index", constraints: AdminConstraint.new
    get "customize/css_html" => "site_customizations#index", constraints: AdminConstraint.new
    get "customize/css_html/:id/:section" => "site_customizations#index", constraints: AdminConstraint.new
    get "customize/colors" => "color_schemes#index", constraints: AdminConstraint.new
    get "customize/permalinks" => "permalinks#index", constraints: AdminConstraint.new
    get "customize/embedding" => "embedding#show", constraints: AdminConstraint.new
    put "customize/embedding" => "embedding#update", constraints: AdminConstraint.new
    get "flags" => "flags#index"
    get "flags/:filter" => "flags#index"
    post "flags/agree/:id" => "flags#agree"
    post "flags/disagree/:id" => "flags#disagree"
    post "flags/defer/:id" => "flags#defer"
    resources :site_customizations, constraints: AdminConstraint.new
    scope "/customize" do
      resources :site_texts, constraints: AdminConstraint.new
      resources :site_text_types, constraints: AdminConstraint.new
      resources :user_fields, constraints: AdminConstraint.new
      resources :emojis, constraints: AdminConstraint.new
    end

    resources :embeddable_hosts, constraints: AdminConstraint.new
    resources :color_schemes, constraints: AdminConstraint.new

    resources :permalinks, constraints: AdminConstraint.new

    get "version_check" => "versions#show"

    resources :dashboard, only: [:index] do
      collection do
        get "problems"
      end
    end

    resources :api, only: [:index], constraints: AdminConstraint.new do
      collection do
        post "key" => "api#create_master_key"
        put "key" => "api#regenerate_key"
        delete "key" => "api#revoke_key"
      end
    end

    resources :backups, only: [:index, :create], constraints: AdminConstraint.new do
      member do
        get "" => "backups#show", constraints: { id: BACKUP_ROUTE_FORMAT }
        delete "" => "backups#destroy", constraints: { id: BACKUP_ROUTE_FORMAT }
        post "restore" => "backups#restore", constraints: { id: BACKUP_ROUTE_FORMAT }
      end
      collection do
        get "logs" => "backups#logs"
        get "status" => "backups#status"
        get "cancel" => "backups#cancel"
        get "rollback" => "backups#rollback"
        put "readonly" => "backups#readonly"
        get "upload" => "backups#check_backup_chunk"
        post "upload" => "backups#upload_backup_chunk"
      end
    end

    resources :badges, constraints: AdminConstraint.new do
      collection do
        get "types" => "badges#badge_types"
        post "badge_groupings" => "badges#save_badge_groupings"
        post "preview" => "badges#preview"
      end
    end

    get "memory_stats"=> "diagnostics#memory_stats", constraints: AdminConstraint.new
    get "dump_heap"=> "diagnostics#dump_heap", constraints: AdminConstraint.new
    get "dump_statement_cache"=> "diagnostics#dump_statement_cache", constraints: AdminConstraint.new

  end # admin namespace

  get "email_preferences" => "email#preferences_redirect", :as => "email_preferences_redirect"
  get "email/unsubscribe/:key" => "email#unsubscribe", as: "email_unsubscribe"
  post "email/resubscribe/:key" => "email#resubscribe", as: "email_resubscribe"

  resources :session, id: USERNAME_ROUTE_FORMAT, only: [:create, :destroy, :become] do
    get 'become'
    collection do
      post "forgot_password"
    end
  end

  get "session/sso" => "session#sso"
  get "session/sso_login" => "session#sso_login"
  get "session/sso_provider" => "session#sso_provider"
  get "session/current" => "session#current"
  get "session/csrf" => "session#csrf"
  get "composer-messages" => "composer_messages#index"

  resources :users, except: [:show, :update, :destroy] do
    collection do
      get "check_username"
      get "is_local_username"
    end
  end

  resources :static
  post "login" => "static#enter"
  get "login" => "static#show", id: "login"
  get "password-reset" => "static#show", id: "password_reset"
  get "faq" => "static#show", id: "faq"
  get "guidelines" => "static#show", id: "guidelines", as: 'guidelines'
  get "tos" => "static#show", id: "tos", as: 'tos'
  get "privacy" => "static#show", id: "privacy", as: 'privacy'
  get "signup" => "list#latest"
  get "login-preferences" => "static#show", id: "login"

  get "users/admin-login" => "users#admin_login"
  put "users/admin-login" => "users#admin_login"
  get "users/admin-login/:token" => "users#admin_login"

  post "users/toggle-anon" => "users#toggle_anon"
  post "users/read-faq" => "users#read_faq"
  get "users/search/users" => "users#search_users"
  get "users/account-created/" => "users#account_created"
  get "users/password-reset/:token" => "users#password_reset"
  put "users/password-reset/:token" => "users#password_reset"
  get "users/activate-account/:token" => "users#activate_account"
  put "users/activate-account/:token" => "users#perform_account_activation", as: 'perform_activate_account'
  get "users/authorize-email/:token" => "users#authorize_email"
  get "users/hp" => "users#get_honeypot_value"
  get "my/*path", to: 'users#my_redirect'

  get "user_preferences" => "users#user_preferences_redirect"

app/controllers/users/omniauth_callbacks_controller.rb
# -*- encoding : utf-8 -*-
require_dependency 'email'
require_dependency 'enum'
require_dependency 'user_name_suggester'

class Users::OmniauthCallbacksController < ApplicationController

  BUILTIN_AUTH = [
    Auth::FacebookAuthenticator.new,
    Auth::GoogleOAuth2Authenticator.new,
    Auth::OpenIdAuthenticator.new("yahoo", "https://me.yahoo.com", trusted: true),
    Auth::GithubAuthenticator.new,
    Auth::TwitterAuthenticator.new
  ]

  skip_before_filter :redirect_to_login_if_required

  layout false

  def self.types
    @types ||= Enum.new(:facebook, :twitter, :google, :yahoo, :github, :persona, :cas)
  end

  # need to be able to call this
  skip_before_filter :check_xhr

  # this is the only spot where we allow CSRF, our openid / oauth redirect
  # will not have a CSRF token, however the payload is all validated so its safe
  skip_before_filter :verify_authenticity_token, only: :complete

  def complete
    auth = request.env["omniauth.auth"]
    auth[:session] = session

    authenticator = self.class.find_authenticator(params[:provider])
    provider = Discourse.auth_providers && Discourse.auth_providers.find{|p| p.name == params[:provider]}

    @auth_result = authenticator.after_authenticate(auth)

    origin = request.env['omniauth.origin']
    if origin.present?
      parsed = URI.parse(@origin) rescue nil
      if parsed
        @origin = parsed.path
      end
    end

    unless @origin.present?
      @origin = Discourse.base_uri("/")
    end

    if @auth_result.failed?
      flash[:error] = @auth_result.failed_reason.html_safe
      return render('failure')
    else
      @auth_result.authenticator_name = authenticator.name
      complete_response_data

      if provider && provider.full_screen_login
        cookies['_bypass_cache'] = true
        flash[:authentication_data] = @auth_result.to_client_hash.to_json
        redirect_to @origin
      else
        respond_to do |format|
          format.html
          format.json { render json: @auth_result.to_client_hash }
        end
      end
    end
  end

  def failure
    flash[:error] = I18n.t("login.omniauth_error")
    render layout: 'no_ember'
  end


  def self.find_authenticator(name)
    BUILTIN_AUTH.each do |authenticator|
      if authenticator.name == name
        raise Discourse::InvalidAccess.new("provider is not enabled") unless SiteSetting.send("enable_#{name}_logins?")
        return authenticator
      end
    end

    Discourse.auth_providers.each do |provider|
      return provider.authenticator if provider.name == name
    end

    raise Discourse::InvalidAccess.new("provider is not found")
  end

  protected

  def complete_response_data
    if @auth_result.user
      user_found(@auth_result.user)
    elsif SiteSetting.invite_only?
      @auth_result.requires_invite = true
    else
      session[:authentication] = @auth_result.session_data
    end
  end

  def user_found(user)
    # automatically activate any account if a provider marked the email valid
    if !user.active && @auth_result.email_valid
      user.toggle(:active).save
    end

    if ScreenedIpAddress.should_block?(request.remote_ip)
      @auth_result.not_allowed_from_ip_address = true
    elsif ScreenedIpAddress.block_admin_login?(user, request.remote_ip)
      @auth_result.admin_not_allowed_from_ip_address = true
    elsif Guardian.new(user).can_access_forum? && user.active # log on any account that is active with forum access
      log_on_user(user)
      Invite.invalidate_for_email(user.email) # invite link can't be used to log in anymore
      session[:authentication] = nil # don't carry around old auth info, perhaps move elsewhere
      @auth_result.authenticated = true
    else
      if SiteSetting.must_approve_users? && !user.approved?
        @auth_result.awaiting_approval = true
      else
        @auth_result.awaiting_activation = true
      end
    end
  end

end

app/views/users/_auto_redirect_home.html.erb
<script language="javascript">
  (function() {
    setTimeout(function() {
      window.location.href = '/';
    }, 2000);
  })();
</script>

app/views/users/account_created.html.erb
<div id='simple-container'>
  <span style="font-size: 16px; line-height: 24px;"><%= @message.html_safe %></span>
</div>

app/views/users/activate_account.html.erb
<div id='simple-container'>
    <h2><%= t 'activation.welcome_to', site_name: SiteSetting.title %></h2>
    <br/>
    <button class='btn' id='activate-account-button'><%= t 'activation.action' %></button>

    <%= form_tag(perform_activate_account_path, method: :put, id: 'activate-account-form') do %>
      <%= hidden_field_tag 'password_confirmation' %>
      <%= hidden_field_tag 'challenge' %>
    <% end %>
</div>

<%- content_for(:no_ember_head) do %>
  <%= script "vendor" %>
<%- end %>

<script language="javascript">
  (function() {
    function activateAccount() {
      $('#activate-account-button').prop('disabled', true);
      $.ajax("<%= path "/users/hp" %>").then(function(hp) {
        $('#password_confirmation').val(hp.value);
        $('#challenge').val(hp.challenge.split("").reverse().join(""));
        $('#activate-account-form').submit();
      }).fail(function() {
        $('#activate-account-button').prop('disabled', false);
      });
    }

    var t0 = new Date().getTime();
    $('#activate-account-button').on('click', function() {
      var diff = new Date().getTime() - t0;

      // Ensure the form has been visible for a few ms before allowing the
      // user to submit.
      if (diff > 50) {
        activateAccount();
      }
    });
  })();
</script>

app/views/users/admin_login.html.erb
<html>
  <head>
    <title>Admin Login</title>
  </head>
  <body>
    <% if @message %>
      <%= @message %>
    <% else %>
      <%=form_tag({}, method: :put) do %>
        <%= label_tag(:email, t('admin_login.email_input')) %>
        <%= text_field_tag(:email) %><br><br>
        <%= submit_tag t('admin_login.submit_button') %>
      <% end %>
    <% end %>
  </body>
</html>

app/views/users/authorize_email.html.erb
<div id="simple-container">
  <%if flash[:error]%>
    <div class='alert alert-error'>
      <%=flash[:error]%>
    </div>
  <%else%>
    <h2><%= t 'change_email.confirmed' %></h2>
    <br>
    <a class="btn" href="/"><%= t('change_email.please_continue', site_name: SiteSetting.title) %></a>
    <%= render partial: 'auto_redirect_home' %>
  <%end%>
</div>

app/views/users/password_reset.html.erb
<div id="simple-container">
  <%if @error%>
    <div class='alert alert-error'>
      <%= @error %>
    </div>
  <%end%>
  <% if @user.present? and @user.errors.any? %>
    <div class='alert alert-error'>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </div>
  <% end %>

  <%if @success%>
    <p>
      <%= @success %>
      <%- if @requires_approval %>
        <%= t 'login.not_approved' %>
      <% else %>
        <br>
        <br>
        <a class="btn" href="<%= path "/" %>"><%= t('password_reset.continue', site_name: SiteSetting.title) %></a>
      <% end %>
    </p>
  <% else %>
    <%if @user.present? %>
      <h3>
        <% if @user.has_password? %>
          <%= t 'password_reset.choose_new' %>
        <% else %>
          <%= t 'password_reset.choose' %>
        <% end %>
      </h3>

      <%=form_tag({}, method: :put) do %>
        <p>
          <span style="display: none;"><input name="username" type="text" value="<%= @user.username %>"></span>
          <input id="user_password" name="password" size="30" type="password" maxlength="<%= User.max_password_length %>" onkeypress="capsLock(event)">
          <label><%= t('js.user.password.instructions', count: SiteSetting.min_password_length) %></label>
        </p>
        <div id="capsLockWarning" class="caps-lock-warning" style="visibility:hidden"><i class="fa fa-exclamation-triangle"></i> <%= t 'js.login.caps_lock_warning' %></div>
        <p>
        <%=submit_tag( @user.has_password? ? t('password_reset.update') : t('password_reset.save'), class: 'btn')%>
        </p>
      <%end%>
    <%end%>
  <%end%>
</div>

<script type="text/javascript">
  document.getElementById('user_password').focus();

  function capsLock(e) {
    kc = e.keyCode?e.keyCode:e.which;
    sk = e.shiftKey?e.shiftKey:((kc == 16)?true:false);
    (((kc >= 65 && kc <= 90) && !sk)||((kc >= 97 && kc <= 122) && sk)) ? document.getElementById('capsLockWarning').style.visibility = 'visible' : document.getElementById('capsLockWarning').style.visibility = 'hidden';
  }
</script>

app/views/users/perform_account_activation.html.erb
<div id='simple-container'>

  <%if flash[:error]%>
    <div class='alert alert-error'>
      <%=flash[:error]%>
    </div>
  <%else%>
    <h2><%= t 'activation.welcome_to', site_name: SiteSetting.title %></h2>
    <br>

    <% if @needs_approval %>
      <p><%= t 'activation.approval_required' %></p>
    <% else %>
      <p><%= t('activation.please_continue') %></p>
      <p><a class="btn" href="<%= path "/" %>"><%= t('activation.continue_button', site_name: SiteSetting.title) -%></a></p>
      <%= render partial: 'auto_redirect_home' %>
    <% end %>
  <%end%>
</div>

app/views/users/send_activation_email.html.erb
<div id='simple-container'>
  <p>
    <% if @user %>
      <%= t 'login.sent_activate_email_again', email: @user.email %>
    <% else %>
      <%
        # We should never get here because we only show the link to resend
        # the activation email if you successfully logged in, but your
        # email hasn't been confirmed.
      %>
      <%= t 'login.incorrect_username_email_or_password' %>
    <% end %>
  </p>
</div>

app/views/users/show.html.erb
<h2><%= @user.username %></h2>

<% unless @restrict_fields %>
<p><%= raw @user.user_profile.bio_processed %></p>
<% end %>

<% content_for :head do %>
  <% if @restrict_fields %>
    <%= raw crawlable_meta_data(title: @user.username, image: @user.small_avatar_url) %>
  <% else %>
    <%= raw crawlable_meta_data(title: @user.username, description: @user.user_profile.bio_summary, image: @user.small_avatar_url) %>
  <% end %>
<% end %>

<% content_for :title do %>
  <%= t("js.user.profile")%> - <%= @user.username %>
<% end %>